# Generated by Django 2.2 on 2020-03-10 03:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devicekey', models.CharField(max_length=32)),
                ('babyname', models.CharField(max_length=32, null=True)),
                ('toyname', models.CharField(max_length=32, null=True)),
                ('avatar', models.FileField(null=True, upload_to='static/avatar')),
                ('createTime', models.TimeField(default=datetime.datetime(2020, 3, 10, 11, 42, 58, 414016))),
                ('bindUser', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'toy',
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=32)),
                ('nickname', models.CharField(max_length=50)),
                ('gender', models.BooleanField(default=1)),
                ('avatar', models.FileField(null=True, upload_to='static/avatar')),
                ('createTime', models.TimeField(default=datetime.datetime(2020, 3, 10, 11, 42, 58, 413018))),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
