# Generated by Django 2.2 on 2020-03-10 09:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toy_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toymodel',
            name='createTime',
            field=models.TimeField(default=datetime.datetime(2020, 3, 10, 17, 35, 43, 394043)),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='createTime',
            field=models.TimeField(default=datetime.datetime(2020, 3, 10, 17, 35, 43, 393047)),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='phone',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
