# Generated by Django 2.2 on 2020-03-10 09:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toy_admin', '0002_auto_20200310_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toymodel',
            name='createTime',
            field=models.TimeField(default=datetime.datetime(2020, 3, 10, 17, 37, 8, 887940)),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='createTime',
            field=models.TimeField(default=datetime.datetime(2020, 3, 10, 17, 37, 8, 886942)),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='gender',
            field=models.CharField(default=1, max_length=10),
        ),
    ]
