# Generated by Django 2.2 on 2020-03-10 12:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toy_admin', '0003_auto_20200310_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musicname', models.CharField(max_length=52)),
                ('classify', models.CharField(max_length=52)),
                ('source', models.CharField(max_length=52)),
                ('musicimage', models.CharField(max_length=255)),
                ('musicurl', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'music',
            },
        ),
        migrations.AlterField(
            model_name='toymodel',
            name='createTime',
            field=models.TimeField(default=datetime.datetime(2020, 3, 10, 20, 18, 15, 833949)),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='createTime',
            field=models.TimeField(default=datetime.datetime(2020, 3, 10, 20, 18, 15, 833949)),
        ),
    ]
